name: Generate thumbnails
on:
  push:
    branches:
      - images
    paths:
      - 'content-img/**/*' # Only run on this path changes
permissions:
  contents: write
jobs:
  generate_thumbnails:
    name: Generate thumbnails
    runs-on: ubuntu-latest
    timeout-minutes: 10 # Should be enough for all runs, GH default is 360 which is unreasonable...
    steps:
      - name: Checkout repository # Check out the repo to access the input image folder.
        uses: actions/checkout@v4
      - name: Process Images
        id: images-1
        uses: subic/ghaction-thumbnails@v1.1 # Tag number optional, breaking changes not expected.
        with: # Arguments:
          source: 'content-img/galerie/cerdanya' # REQUIRED
          output: 'static/img//galerie/cerdanya' # REQUIRED
          sizes: 1920 # REQUIRED
          extensions: 'jpg, jpeg, png, webp, gif, tiff'
          subfolder: ''
          filename: '%F'
          fit: 'cover'
          position: 'centre'
          enlarge: 'false'
          overwrite: 'false'
      - name: Process Images thumb
        id: images-thumb-1
        uses: subic/ghaction-thumbnails@v1.1 # Tag number optional, breaking changes not expected.
        with: # Arguments:
          source: 'content-img/galerie/cerdanya' # REQUIRED
          output: 'static/img//galerie/cerdanya' # REQUIRED
          sizes: 246x310 # REQUIRED
          extensions: 'jpg, jpeg, png, webp, gif, tiff'
          subfolder: ''
          filename: '%N-thumb.%E'
          fit: 'cover'
          position: 'centre'
          enlarge: 'false'
          overwrite: 'false'
      - name: Process Images
        id: images-2
        uses: subic/ghaction-thumbnails@v1.1 # Tag number optional, breaking changes not expected.
        with: # Arguments:
          source: 'content-img/galerie/ziegenhain' # REQUIRED
          output: 'static/img//galerie/ziegenhain' # REQUIRED
          sizes: 1920 # REQUIRED
          extensions: 'jpg, jpeg, png, webp, gif, tiff'
          subfolder: ''
          filename: '%F'
          fit: 'cover'
          position: 'centre'
          enlarge: 'false'
          overwrite: 'false'
      - name: Process Images thumb
        id: images-thumb-2
        uses: subic/ghaction-thumbnails@v1.1 # Tag number optional, breaking changes not expected.
        with: # Arguments:
          source: 'content-img/galerie/ziegenhain' # REQUIRED
          output: 'static/img//galerie/ziegenhain' # REQUIRED
          sizes: 246x310 # REQUIRED
          extensions: 'jpg, jpeg, png, webp, gif, tiff'
          subfolder: ''
          filename: '%N-thumb.%E'
          fit: 'cover'
          position: 'centre'
          enlarge: 'false'
          overwrite: 'false'
      - uses: EndBug/add-and-commit@v9
        with:
          message: Update thumbnails
          committer_name: "${{github.actor}}"
          committer_email: "${{github.actor}}@users.noreply.github.com"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  